# Generated by Django 3.2.9 on 2021-12-03 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revapp', '0002_auto_20211203_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='revapp.article'),
        ),
    ]
