# Generated by Django 3.2.9 on 2021-11-15 23:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revapp', '0004_alter_article_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
