# Generated by Django 3.2.9 on 2021-12-03 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revapp', '0005_auto_20211203_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='article',
        ),
    ]
