# Generated by Django 3.2.9 on 2021-11-15 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revapp', '0005_alter_article_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fans',
            field=models.ManyToManyField(blank=True, related_name='liked_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
