# Generated by Django 3.2.8 on 2021-11-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
                ('bro', models.BigIntegerField(default=0)),
                ('sis', models.BigIntegerField(default=0)),
            ],
        ),
    ]
