# Generated by Django 3.2.8 on 2021-11-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
